name = "AlgebraicPetri"
uuid = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
license = "MIT"
authors = ["Micah Halter <micah@mehalter.com>"]
version = "0.9.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"

[weakdeps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[extensions]
AlgebraicPetriCatalystExt = "Catalyst"
AlgebraicPetriModelingToolkitExt = "ModelingToolkit"
AlgebraicPetriOrdinaryDiffEqExt = "OrdinaryDiffEq"

[compat]
Catalyst = "13"
Catlab = "0.15.5"
GeneralizedGenerated = "0.3"
LabelledArrays = "1"
ModelingToolkit = "8"
OrdinaryDiffEq = "6"
julia = "1.9"
