name = "AlgebraicPetri"
uuid = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
license = "MIT"
authors = ["Micah Halter <micah@mehalter.com>"]
version = "0.8.10"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Petri = "4259d249-1051-49fa-8328-3f8ab9391c33"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extensions]
AlgebraicPetriCatalystExt = "Catalyst"
AlgebraicPetriModelingToolkitExt = "ModelingToolkit"
AlgebraicPetriPetriExt = "Petri"

[compat]
Catalyst = "13"
Catlab = "0.14.16"
DataStructures = "0.18"
GeneralizedGenerated = "0.3"
ModelingToolkit = "8"
Petri = "1"
Requires = "1"
StatsBase = "0.33,0.34"
julia = "1.6"
