name: Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # GR backend fix for Plots, discussed in https://github.com/jheinen/GR.jl/issues/422
      GKSwstype: nul
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - name: "Install system dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install graphviz pdf2svg
          sudo apt-get install texlive-latex-base texlive-latex-extra texlive-binaries texlive-pictures texlive-luatex
      - name: "Install Julia dependencies"
        run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'
      - name: "Build and deploy docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl
